CREATE TABLE IF NOT EXISTS top_games_2026 (
    app_id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    release_date DATE,
    coming_soon BOOLEAN,
    price_usd DECIMAL(10,2),
    is_free BOOLEAN,
    discount_pct DECIMAL(10,2),
    developer VARCHAR(255),
    publisher VARCHAR(255),
    genres VARCHAR(255),
    categories VARCHAR(255),
    tags VARCHAR(255),
    windows BOOLEAN,
    mac BOOLEAN,
    linux BOOLEAN,
    metacritic_score DECIMAL(10,2),
    recommendations INT,
    positive_reviews INT,
    negative_reviews INT,
    estimated_owners VARCHAR(255),
    avg_playtime_forever INT,
    avg_playtime_2weeks INT,
    median_playtime INT,
    peak_ccu INT,
    required_age INT,
    dlc_count INT,
    achievements INT,
    short_description VARCHAR(255),
    header_image VARCHAR(255),
    platforms VARCHAR(255),
    min_estimated_owners INT,
    max_estimated_owners INT,
    avg_estimated_owners DECIMAL(10,2),
    peak_ccu_rank INT,
    gold_ingest_date TIMESTAMP
)